### ISSUE TITLE
an issue related to tab display

### ISSUE THREAD

**Issue by yiiyahui** [de-vri-es/thunderbird-real-system-theme#1]
When a tab is opened, it will be displayed above the window. this is not an issue in the default theme.
![Screenshot 2023-08-08 174431](https://github.com/de-vri-es/thunderbird-real-system-theme/assets/30188835/e337504b-1460-4bed-b51b-cff3026e6a22)
V115.1.0

**Comment by de-vri-es** [comment]
Ah yeah.. hmm, I moved the unified toolbar below the tabs because I like that more, but now I see it also moves the window buttons down, which isn't really a good style..

**Comment by yiiyahui** [comment]
Yes, if the window buttons and tabs are on the same row, this issue doesn't exist. this theme maintains consistent colors with both thunderbird and the system theme.

**Comment by de-vri-es** [comment]
Should be fixed in 0.1.2. Thanks for reporting the issue!

**Comment by yiiyahui** [comment]
OK!Thank you for fixing it.
